### PR TITLE
allow vertices to have weights and attributes

### PR DESCRIPTION
**Pull request by tobikris**
This adds the possibility for vertices to have weights and attributes - just like edges.
It solves #32 and is based on the idea from the issue.
Graphs store the vertices' properties in a map based on the hash value.

### CODE REVIEW

**Comment by dominikbraun** [comment]
Thanks! Supporting functional options in `AddVertex` makes sense and is consistent with the edge API, so this is a nice suggestion.

I'll take a look soon. One thing that is yet to be clarified is how these changes affect #50, and whether this PR or #50 has precedence.

**Comment by geoah** [comment]
Owh this looks great!

@dominikbraun happy to rebase #50 once this is merged, this seems like it's closer to merging.

Small suggestion, feel free to ignore it: I wonder if it would make any sense to make the `VertexProperties(hash K) (VertexProperties, error)` (or even the `Vertex()` one) to return both the vertex and the properties. ie `VertexWithProperties(hash K) (T, VertexProperties, error)` so that there is an alternative for asking for both instead of having to call two methods. For most of my usecases I don't think I'd ever need just the properties, but that might be a niche.

**Comment by tobikris** [comment]
> Small suggestion, feel free to ignore it: I wonder if it would make any sense to make the `VertexProperties(hash K) (VertexProperties, error)` (or even the `Vertex()` one) to return both the vertex and the properties. ie `VertexWithProperties(hash K) (T, VertexProperties, error)` so that there is an alternative for asking for both instead of having to call two methods. For most of my usecases I don't think I'd ever need just the properties, but that might be a niche.

Thanks. I thought about this as well and decided against returning the properties as well to remain somewhat compatible. But I would be fine with implementing it in any of the mentioned ways. Your call, @dominikbraun

**Comment by dominikbraun** [comment]
> > Small suggestion, feel free to ignore it: I wonder if it would make any sense to make the `VertexProperties(hash K) (VertexProperties, error)` (or even the `Vertex()` one) to return both the vertex and the properties. ie `VertexWithProperties(hash K) (T, VertexProperties, error)` so that there is an alternative for asking for both instead of having to call two methods. For most of my usecases I don't think I'd ever need just the properties, but that might be a niche.
> 
> Thanks. I thought about this as well and decided against returning the properties as well to remain somewhat compatible. But I would be fine with implementing it in any of the mentioned ways. Your call, @dominikbraun

Good question. I think both `VertexProperties(K) (VertexProperties, error)` and `VertexWithProperties(K) (T, VertexProperties, error)` would be fine.

However, when using a library, I personally don't like having to handle an error after each and every line. This is why I, as a user, would probably prefer this:

```go
vertex, properties, err := g.VertexWithProperties(hash)
if err != nil {
    panic(err)
}
```

Over this:

```go
vertex, err := g.Vertex(hash)
if err != nil {
    panic(err)
}

properties, err := g.VertexProperties(hash)
if err != nil {
    panic(err)
}
```

Because retrieving the vertex properties without the vertex itself should be more of an edge case, I consider this a viable approach. One counterargument would be that `VertexWithProperties` looks like a primitive getter function and hides some complexity, but retrieving a vertex is an O(1) operation, so...

That's why I probably would prefer `VertexWithProperties` (or `VertexAndProperties`?), but either is fine.

**Comment by tobikris** [comment]
I like the `VertexWithProperties` version most and changed the code accordingly.

**Review by dominikbraun — APPROVED** [review]

**Comment by tobikris** [comment]
Thanks!

In https://github.com/dominikbraun/graph/commit/1941d0eb2f43aa37ea63feeb7ac905a465be2045 in line 12 the method name is incorrect. Maybe you could fix this?

**Comment by dominikbraun** [comment]
> Thanks!
> 
> In [1941d0e](https://github.com/dominikbraun/graph/commit/1941d0eb2f43aa37ea63feeb7ac905a465be2045) in line 12 the method name is incorrect. Maybe you could fix this?

Good catch, thanks!

**Comment by dominikbraun** [comment]
This change has been released with [graph v0.13.0](https://github.com/dominikbraun/graph/releases/tag/v0.13.0).

**Pull request merged**
