### PR TITLE
Translate the README into Chinese.

### PR DESCRIPTION
**Pull request by JackyYangPassion**
for #121

### CODE REVIEW

**Comment by dominikbraun** [comment]
非常感谢，太棒了！

**Review by dominikbraun — APPROVED** [review]
非常感谢，太棒了！There's no way to actually review this for me because my Chinese is too bad, but I'm going to approve it!

**Comment by williamfzc** [comment]
I have reviewed the Chinese version. Everything looks good.

**Comment by dominikbraun** [comment]
@williamfzc Thanks a lot! In case you feel that there is something that could be improved, feel free to open a PR.

**Comment by williamfzc** [comment]
> @williamfzc Thanks a lot! In case you feel that there is something that could be improved, feel free to open a PR.

A small typo:

`About` in https://github.com/dominikbraun/graph
"一个款用于创建通用图数据结构、对其进行修改、分析和可视化的库。"

In our eyes it may looks like:
"A A library for creating generic graph data structures"

The "个” Should be removed:
"一款用于创建通用图数据结构、对其进行修改、分析和可视化的库。"

**Comment by dominikbraun** [comment]
@williamfzc Thanks, I've fixed that.

**Pull request merged**
